import './SearchRowBottom.css';

import Select from '../../../../../../components/common/Select/Select';
import { useTranslation } from 'react-i18next';

import { MdKeyboardArrowDown } from "react-icons/md";

function SearchRowBottom({
    handleChangeInput,
    formInput,
    setFormInput
}){
    const {t} = useTranslation();
    return(
        <div className='modal-search-row-bottom'>
            <Select
                label={t('eligibility:candidateEligibility')}
                value={formInput.eligibility}
                endIcon={<MdKeyboardArrowDown/>}
                options={[
                    {
                        value:'',
                        label:`${t('common:any')}`
                    },
                    {
                        value:'eligible',
                        label:`${t('eligibility:eligible')}`
                    },
                    {
                        value:'ineligible',
                        label:`${t('eligibility:ineligible')}`
                    },
                    {
                        value:'pending',
                        label:`${t('eligibility:pending')}`
                    }
                ]}
                className='search-consultation-eligibility'
                onChange={handleChangeInput('eligibility')}
            />
            <Select
                label={t('status:consultationResult')}
                value={formInput.consultationStatus}
                endIcon={<MdKeyboardArrowDown/>}
                options={[
                    {
                        value:'',
                        label:`${t('common:any')}`
                    },
                    {
                        value:'agreed',
                        label:`${t('status:agreed')}`
                    },
                    {
                        value:'considering',
                        label:`${t('status:considering')}`
                    },
                    {
                        value:'notInterested',
                        label:`${t('status:notInterested')}`
                    },
                    {
                        value:'undecided',
                        label:`${t('status:undecided')}`
                    },
                    {
                        value:'familyApproval',
                        label:`${t('status:familyApproval')}`
                    }
                ]}
                className='search-consultation-status'
                onChange={handleChangeInput('consultationStatus')}
            />
            <Select
                label={t('candidate:documentStatus')}
                value={formInput.documentStatus}
                endIcon={<MdKeyboardArrowDown/>}
                options={[
                    {
                        value:'',
                        label:`${t('common:any')}`
                    },
                    {
                        value:'submited',
                        label:`${t('common:submitted')}`
                    },
                    {
                        value:'unsubmited',
                        label:`${t('common:unsubmitted')}`
                    },
                ]}
                onChange={handleChangeInput('documentStatus')}
            />
            <Select
                label={t('result:assessment')}
                value={formInput.examStatus}
                endIcon={<MdKeyboardArrowDown/>}
                options={[
                    {
                        value:'',
                        label:`${t('common:any')}`
                    },
                    {
                        value:'passed',
                        label:`${t('result:passed')}`
                    },
                    {
                        value:'failedRetest',
                        label:`${t('result:failedRetest')}`
                    },
                    {
                        value:'failedNonRetest',
                        label:`${t('result:failedNonRetest')}`
                    },
                    {
                        value:'postponed',
                        label:`${t('result:postponed')}`
                    },
                    {
                        value:'absent',
                        label:`${t('result:absent')}`
                    },
                    {
                        value:'enrolled',
                        label:`${t('result:enrolled')}`
                    },
                    {
                        value:'NotEnrolled',
                        label:`${t('result:notEnrolled')}`
                    },
                ]}
                className='search-consultation-exam-status'
                onChange={handleChangeInput('examStatus')}
            />
        </div>
    )
}

export default SearchRowBottom;